---
name: ci

"on":
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  rspec:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, macos-15]
        ruby: [2.6, 2.6.3, 2.6.8, 3.0.0, 3.1.2]
        exclude:
          - os: macos-14
            ruby: 2.6.3
          - os: macos-15
            ruby: 2.6
          - os: macos-15
            ruby: 2.6.3
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rspec ci.sh
        run: |
          ./script/ci.sh
