---
name: ci

"on":
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  rspec:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, macos-15]
        ruby: [3.1.0, 3.1.2, 3.1.4, 3.3.5, 3.4.0]
            
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rspec ci.sh
        run: |
          ./script/ci.sh
